# Generated by Django 2.2.7 on 2021-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210103_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(default=1, max_length=50, verbose_name='المحافظة: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_details',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان بالتفصيل: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_specialist',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص في؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=50, verbose_name='الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name='نبذه عنك: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار '),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=1, max_length=50, verbose_name='عدد ساعات العمل: '),
            preserve_default=False,
        ),
    ]
