# Generated by Django 2.2.7 on 2021-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210103_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='وقت الإنضمام :'),
        ),
    ]
