# Generated by Django 2.2.7 on 2021-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_type_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('طب الأطفال', 'طب الأطفال'), ('طب الأنف والأذن والحنجرة', 'طب الأنف والأذن والحنجرة'), ('طب باطني', 'طب باطني'), ('طب التوليد والنسائيات', 'طب التوليد والنسائيات'), ('طب العيون', 'طب العيون'), ('أسنان', 'أسنان'), ('طب الجهاز البولي', 'طب الجهاز البولي'), ('طب الطوارئ الدولي', 'طب الطوارئ الدولي'), ('طب الطوارئ', 'طب الطوارئ')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
